# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

strategy:
  matrix:
    #linux:
    #  imageName: 'ubuntu-16.04'
    #mac:
      #imageName: 'macos-10.14'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

variables:
  project: '**/*.csproj'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'
  
  Major: '0'
  Minor: '0'
  Patch: '1'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    workingDirectory: '$(System.DefaultWorkingDirectory)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    arguments: '--configuration $(BuildConfiguration)'


# - task: DotNetCoreCLI@2
#   inputs:
#    publishWebProjects: False
#    command: 'publish'
#    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#    zipAfterPublish: True


- task: DotNetCoreCLI@2
  inputs:
   command: 'pack'
   packagesToPack: '**/*.csproj'
   nobuild: true
   arguments: |
              '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) '
              '-p:PackageVersion=$(Major).$(Minor).$(Patch)'
   versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'




# - task: NuGetCommand@2
#   inputs:
   
#     command: 'pack'
#     packagesToPack: '**/*.csproj'
#     versioningScheme: 'off'
#     includeReferencedProjects: true



