# .NET core build pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: '**/*.csproj'
  BuildConfiguration: 'Release'
  XamlColorSchemeGeneratorVersion: ''
 

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.5.1'


- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.100'
    workingDirectory: '$(System.DefaultWorkingDirectory)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
   command: 'pack'
   packagesToPack: '**/*.csproj'
   nobuild: true
   arguments: |
              '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) '
   versioningScheme: 'byPrereleaseNumber'


- task: NuGetCommand@2
  inputs:
    command: 'push'
    feedsToUse: 'select' 
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget AvaloniaExtendedToolkit'
    allowPackageConflicts: true
    versioningScheme: off





# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'







